euclid:
	gcc -ansi -o euclid euclid.c

euclidNegative:
	gcc -ansi -o euclidNegative euclidNegative.c

euclidStruct:
	gcc -ansi -o euclidStruct euclidStruct.c

intConvert:
	gcc -ansi -o intConvert intConvert.c

decToBinary:
	gcc -ansi -o decToBinary decToBinary.c

euclidAllTheValues:
	gcc -ansi -o euclidAllTheValues euclidAllTheValues.c

euclidOfThree:
	gcc -ansi -o euclidOfThree euclidOfThree.c

euclidLargestPair:
	gcc -ansi -o euclidLargestPair euclidLargestPair.c

clean:
	rm -f euclid
	rm -f euclidNegative
	rm -f euclidStruct
	rm -f intConvert
	rm -f decToBinary
	rm -f euclidAllTheValues
	rm -f euclidOfThree
	rm -f euclidLargestPair